/**
 * Rich Fallback Insight — deeply personalized per-sign content
 * Used when Gemini API is unavailable. Every birthday produces unique text.
 */
import type { UserProfile } from './mock-astrology-data';

const S: Record<string, { soul: string; drive: string; shadow: string; love: string; career: string; body: string }> = {
  Aries: { soul: 'The Initiator', drive: 'raw courage and competitive fire', shadow: 'impatience and burning bridges before they are fully built', love: 'a partner who matches your intensity without trying to tame it', career: 'leadership, entrepreneurship, crisis management, or competitive strategy', body: 'head tension, migraines, and adrenal burnout from chronic overdrive' },
  Taurus: { soul: 'The Builder', drive: 'sensory mastery and material security', shadow: 'stubbornness disguised as patience and resistance to necessary change', love: 'a partner who provides stability while awakening your dormant sensuality', career: 'finance, luxury goods, architecture, or land-based ventures', body: 'throat issues, thyroid imbalance, and stress-driven comfort eating' },
  Gemini: { soul: 'The Messenger', drive: 'intellectual stimulation and social versatility', shadow: 'scattered energy and using humor to avoid emotional depth', love: 'a partner who stimulates your mind and tolerates your need for variety', career: 'media, writing, education, sales, or technology communication', body: 'nervous system overload, insomnia, and respiratory sensitivity' },
  Cancer: { soul: 'The Nurturer', drive: 'emotional security and creating sanctuary', shadow: 'passive-aggression and using care as a form of control', love: 'a partner who makes you feel safe enough to stop self-protecting', career: 'healthcare, hospitality, real estate, or counseling', body: 'stomach sensitivity, water retention, and chest tightness under stress' },
  Leo: { soul: 'The Sovereign', drive: 'creative self-expression and heartfelt recognition', shadow: 'ego fragility disguised as unshakable confidence', love: 'a partner who genuinely admires you without competing for the spotlight', career: 'entertainment, leadership, luxury brands, or creative direction', body: 'heart palpitations, back tension, and vitality crashes after overperformance' },
  Virgo: { soul: 'The Analyst', drive: 'precision, devoted service, and systemic improvement', shadow: 'paralyzing perfectionism and relentless critical self-talk', love: 'a partner who appreciates your devotion without exploiting your giving nature', career: 'healthcare, data science, editing, or process optimization', body: 'digestive sensitivity, anxiety loops, and stress-triggered skin reactions' },
  Libra: { soul: 'The Diplomat', drive: 'harmony, aesthetic beauty, and relational balance', shadow: 'chronic indecision and losing your identity inside relationships', love: 'a partner who brings decisiveness while honoring your need for beauty and fairness', career: 'law, design, mediation, public relations, or luxury curation', body: 'kidney stress, lower back pain, and hormonal fluctuations under pressure' },
  Scorpio: { soul: 'The Transformer', drive: 'psychological depth and regenerative power', shadow: 'control obsession and trust wounds that unconsciously push intimacy away', love: 'a partner brave enough to meet your emotional depth without flinching or retreating', career: 'psychology, investigative research, finance, or crisis intervention', body: 'reproductive system sensitivity, detox congestion, and deeply held muscular tension' },
  Sagittarius: { soul: 'The Explorer', drive: 'freedom, philosophical meaning, and horizon expansion', shadow: 'commitment avoidance and brutal honesty delivered without empathy', love: 'a partner who shares your hunger for growth without caging your freedom', career: 'publishing, international business, higher education, or adventure industries', body: 'hip and thigh tension, liver sensitivity, and physical restlessness' },
  Capricorn: { soul: 'The Architect', drive: 'legacy building, earned authority, and structural mastery', shadow: 'emotional suppression and using workaholism as an identity shield', love: 'a partner who softens your armor without disrespecting your ambition', career: 'executive leadership, engineering, government, or wealth management', body: 'bone and joint stress, teeth grinding, and chronic tension from carrying too much' },
  Aquarius: { soul: 'The Visionary', drive: 'innovation, humanitarian progress, and intellectual freedom', shadow: 'emotional detachment disguised as enlightened independence', love: 'a partner who gives you space while remaining emotionally present and warm', career: 'technology, social enterprise, scientific research, or systemic reform', body: 'circulation issues, ankle vulnerability, and nervous system voltage spikes' },
  Pisces: { soul: 'The Mystic', drive: 'spiritual connection, creative transcendence, and compassion', shadow: 'boundary dissolution and escapism into fantasy when reality feels too sharp', love: 'a partner who protects your sensitivity without dismissing your intuition as irrational', career: 'arts, healing professions, film, music, or spiritual counseling', body: 'immune sensitivity, foot problems, and absorbing other people\'s emotional residue' },
};

const H: Record<number, string> = {
  1: 'identity and self-presentation',
  2: 'finances and self-worth',
  3: 'communication and learning',
  4: 'home and emotional foundations',
  5: 'creativity and romance',
  6: 'daily routines and health',
  7: 'partnerships and commitment',
  8: 'transformation and shared resources',
  9: 'higher learning and travel',
  10: 'career and public reputation',
  11: 'community and future vision',
  12: 'spirituality and the unconscious',
};

export function getRichFallbackInsight(profile: UserProfile) {
  const sun = profile.sun.sign;
  const moon = profile.moon.sign;
  const rising = profile.rising.sign;
  const sd = S[sun] || S['Aries'];
  const md = S[moon] || S['Cancer'];
  const rd = S[rising] || S['Libra'];
  const sunH = H[profile.sun.house] || H[1];
  const moonH = H[profile.moon.house] || H[4];
  const risingH = H[1];
  const el = profile.elements;
  const dominant = el.fire > el.earth && el.fire > el.air && el.fire > el.water ? 'Fire'
    : el.earth > el.air && el.earth > el.water ? 'Earth'
    : el.air > el.water ? 'Air' : 'Water';
  const weakest = Object.entries(el).sort((a, b) => a[1] - b[1])[0][0];
  const venus = profile.planets?.find(p => p.name === 'Venus');
  const mars = profile.planets?.find(p => p.name === 'Mars');
  const saturn = profile.planets?.find(p => p.name === 'Saturn');
  const vSign = venus?.sign || 'Libra';
  const mSign = mars?.sign || 'Aries';
  const satSign = saturn?.sign || 'Capricorn';

  return {
    nickname: `${sd.soul} with a ${moon} Heart`,
    coreQuote: `Your ${sun} fire is filtered through a ${moon} emotional lens and presented to the world as ${rising} — a combination that makes you unforgettable to those who truly see you.`,
    summary: `Your Sun in ${sun} (House ${profile.sun.house} — ${sunH}) marks you as ${sd.soul}. At your core, you are driven by ${sd.drive}. Your Moon in ${moon} (House ${profile.moon.house} — ${moonH}) reveals that emotionally, you process the world through ${md.drive}. Meanwhile, your Rising Sign in ${rising} means the world first encounters you as ${rd.soul} — someone shaped by ${rd.drive}.\n\nThis creates a fascinating internal architecture: your ${sun} ambition is filtered through ${moon} emotional needs and packaged in a ${rising} exterior. When these layers align, you are magnetic and unstoppable. When they conflict, you feel pulled between who you are, who you feel yourself to be, and who others expect you to see. The work of your lifetime is integration — not choosing one layer over another, but building bridges between all three.\n\n### Next Steps\n- Journal on where your ${sun} desires and ${moon} needs currently conflict\n- Notice when your ${rising} mask feels protective vs. when it feels like a cage\n- Practice expressing your ${moon} emotional truth through your ${sun} creative channel`,

    career: `With your Sun in the ${profile.sun.house}th House (${sunH}), your career fulfillment is deeply tied to ${sunH}. Your chart architecture points toward ${sd.career} as natural professional domains. Mars in ${mSign} gives your work style a ${S[mSign]?.drive || 'focused intensity'} quality — you are most productive when ${mSign === 'Aries' || mSign === 'Leo' || mSign === 'Sagittarius' ? 'given autonomy and competitive stakes' : mSign === 'Taurus' || mSign === 'Virgo' || mSign === 'Capricorn' ? 'working within clear structures toward tangible outcomes' : mSign === 'Gemini' || mSign === 'Libra' || mSign === 'Aquarius' ? 'collaborating on intellectually stimulating projects' : 'emotionally invested in meaningful work'}.\n\nSaturn in ${satSign} suggests your greatest career lessons come through ${S[satSign]?.shadow || 'facing limitations with maturity'}. The professional authority you build after age 30 will far exceed anything before it — Saturn rewards patience and structural integrity.\n\n### Next Steps\n- Identify one career move that aligns with your ${sunH} theme this quarter\n- Use your Mars in ${mSign} energy for high-priority tasks before 2pm daily\n- Build one Saturn-approved system (documentation, mentorship, certification) this month`,

    relationships: `Your Moon in ${moon} (House ${profile.moon.house}) is the key to understanding your love patterns. You need ${md.love}. Venus in ${vSign} shapes what you find beautiful and attractive — you are drawn to ${S[vSign]?.love || 'partners who balance strength with warmth'}.\n\nYour attachment style is colored by your ${moon} Moon: ${moon === 'Cancer' || moon === 'Pisces' || moon === 'Scorpio' ? 'you tend toward anxious attachment — craving deep merger while fearing abandonment' : moon === 'Aquarius' || moon === 'Sagittarius' || moon === 'Aries' ? 'you lean toward avoidant attachment — needing freedom while secretly wanting someone to stay' : 'you oscillate between secure and anxious patterns depending on how safe your partner makes you feel'}.\n\n**What Your Partner Needs to Know About You:** Your ${moon} Moon means you feel everything more deeply than you show. When you withdraw, it is not rejection — it is overwhelm. The fastest way to reach you is through ${moon === 'Cancer' || moon === 'Taurus' || moon === 'Pisces' ? 'physical comfort, a warm meal, or simply sitting together in silence' : moon === 'Gemini' || moon === 'Aquarius' || moon === 'Libra' ? 'honest conversation — talking IS your love language' : 'showing up consistently — your trust is earned through actions, not words'}.\n\n### Next Steps\n- Name your attachment pattern honestly to your closest person this week\n- Practice one Venus in ${vSign} self-love ritual (beauty, pleasure, receiving)\n- Express one ${moon} Moon need you have been silently hoping someone would guess`,

    wealth: `Your financial blueprint is shaped by your ${dominant} dominant element (Fire ${el.fire}% / Earth ${el.earth}% / Air ${el.air}% / Water ${el.water}%). ${dominant === 'Fire' ? 'You earn through bold ventures and risk-taking, but must discipline yourself to save and invest rather than burn through resources.' : dominant === 'Earth' ? 'You have a natural gift for accumulating wealth through patience and tangible assets. Your challenge is avoiding scarcity mentality when you already have enough.' : dominant === 'Air' ? 'Your wealth comes through ideas, networks, and intellectual property. Your challenge is converting brilliant concepts into actual cash flow.' : 'Your wealth is tied to emotional intelligence — you earn through empathy, creativity, and healing. Your challenge is charging what you are actually worth.'}\n\nSaturn in ${satSign} indicates that financial maturity arrives through ${S[satSign]?.drive || 'discipline and structure'}. The money lessons you learn before 35 become the wealth foundation of your 40s and beyond.\n\n### Next Steps\n- Set up one automated savings system aligned with your ${dominant} element strength\n- Audit one financial leak that your ${weakest} element weakness creates\n- Make one wealth-building move that your Saturn in ${satSign} would approve of`,

    health: `Your chart highlights ${sd.body} as your primary physical vulnerability with Sun in ${sun}. Your Moon in ${moon} adds ${md.body} when emotional stress accumulates.\n\nYour ${dominant} dominant element means your body runs ${dominant === 'Fire' ? 'hot and fast — you need cooling practices (swimming, meditation, anti-inflammatory foods) to prevent burnout' : dominant === 'Earth' ? 'steady but heavy — you need movement and lightness (dance, hiking, intermittent fasting) to prevent stagnation' : dominant === 'Air' ? 'electric and scattered — you need grounding practices (weight training, routine meals, digital detox) to calm your nervous system' : 'fluid and porous — you need firm boundaries (alone time, energy clearing, physical exercise) to prevent absorbing other people\'s stress'}.\n\nYour weakest element is ${weakest}, which means you must consciously cultivate ${weakest === 'fire' ? 'physical movement and passionate engagement' : weakest === 'earth' ? 'routine, nutrition discipline, and rest' : weakest === 'air' ? 'social connection and mental stimulation' : 'emotional expression and creative release'} to stay balanced.\n\n### Next Steps\n- Address your ${sun} vulnerability: schedule one preventive health action this week\n- Create one ${dominant}-balancing daily ritual (10 minutes minimum)\n- Strengthen your ${weakest} element with one specific weekly practice`,

    strengths: `Your elemental distribution (Fire ${el.fire}% / Earth ${el.earth}% / Air ${el.air}% / Water ${el.water}%) reveals three hidden superpowers:\n\n**1. ${sd.soul} Magnetism:** Your ${sun} Sun combined with ${rising} Rising creates a rare blend of ${sd.drive} and ${rd.drive}. People sense this duality and find it compelling — you are both fire and mystery.\n\n**2. Emotional Intelligence:** Your ${moon} Moon in the ${profile.moon.house}th House (${moonH}) gives you an uncanny ability to read emotional undercurrents. You know what people feel before they say it. This is not imagination — it is a genuine perceptual gift.\n\n**3. ${dominant} Dominance Edge:** With ${dominant} as your strongest element at ${Math.max(el.fire, el.earth, el.air, el.water)}%, you have a devastating natural advantage in ${dominant === 'Fire' ? 'decisive action under pressure — you thrive exactly when others freeze' : dominant === 'Earth' ? 'building lasting, tangible results — you finish what others abandon' : dominant === 'Air' ? 'connecting ideas and people — you see patterns that are invisible to others' : 'emotional resonance — you create trust and intimacy faster than anyone in the room'}.\n\n### Next Steps\n- Name your top strength out loud to someone this week — own it publicly\n- Use your ${moon} Moon emotional intelligence deliberately in one meeting or conversation\n- Double down on your ${dominant} element advantage in one professional context`,

    warnings: `Your chart reveals three patterns that quietly limit your growth:\n\n**1. ${sd.shadow}:** This is your ${sun} Sun shadow. It shows up most when you are stressed, tired, or feeling unseen. The antidote is not suppression — it is awareness followed by a one-breath pause before reacting.\n\n**2. ${md.shadow}:** This is your ${moon} Moon shadow — the emotional habit that runs on autopilot. It was probably adaptive in childhood but now creates unnecessary friction in adult relationships.\n\n**3. ${weakest} Element Deficiency:** With ${weakest} as your weakest element, you chronically underinvest in ${weakest === 'fire' ? 'taking bold action, asserting boundaries, and pursuing passion' : weakest === 'earth' ? 'practical follow-through, financial discipline, and physical self-care' : weakest === 'air' ? 'objective analysis, social networking, and intellectual growth' : 'emotional processing, creative expression, and spiritual connection'}. This blind spot compounds silently over years.\n\n### Next Steps\n- Catch your ${sun} shadow ONCE this week in real-time — just notice it, no judgment\n- Ask one trusted person if they recognize your ${moon} Moon pattern in you\n- Schedule one weekly activity that specifically builds your ${weakest} element`,
  };
}
